package jef.database.innerpool;

import java.sql.Array;
import java.sql.Blob;
import java.sql.CallableStatement;
import java.sql.Clob;
import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.NClob;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLClientInfoException;
import java.sql.SQLException;
import java.sql.SQLWarning;
import java.sql.SQLXML;
import java.sql.Savepoint;
import java.sql.Statement;
import java.sql.Struct;
import java.util.Map;
import java.util.Properties;

import jef.database.ConnectionFactory;
import jef.database.DebugUtil;
import jef.database.WrappedConnection;
import jef.database.jdbc.GenerateKeyReturnOper;
import jef.database.routing.jdbc.JPreparedCall;
import jef.database.routing.jdbc.JPreparedStatement;
import jef.database.routing.jdbc.JStatement;

/**
 * 带SQL解析和路由功能的Connection
 * 
 * @author jiyi
 * 
 */
public class JConnection implements Connection {
	@SuppressWarnings("unused")
	private ConnectionFactory connectionFactory;
	private WrappedConnection connection;

	public JConnection(ConnectionFactory db) {
		this.connectionFactory = db;
		this.connection = db.startTransaction().setAutoCommit(true);
	}

	@Override
	public Statement createStatement() throws SQLException {
		return createStatement(ResultSet.TYPE_FORWARD_ONLY, ResultSet.CONCUR_READ_ONLY, ResultSet.CLOSE_CURSORS_AT_COMMIT);
	}

	@Override
	public PreparedStatement prepareStatement(String sql) throws SQLException {
		return prepareStatement(sql, ResultSet.TYPE_FORWARD_ONLY, ResultSet.CONCUR_READ_ONLY, ResultSet.CLOSE_CURSORS_AT_COMMIT);
	}

	@Override
	public CallableStatement prepareCall(String sql) throws SQLException {
		return prepareCall(sql, ResultSet.TYPE_FORWARD_ONLY, ResultSet.CONCUR_READ_ONLY, ResultSet.CLOSE_CURSORS_AT_COMMIT);
	}

	@Override
	public void setAutoCommit(boolean autoCommit) throws SQLException {
		connection.setAutoCommit(autoCommit);
	}

	@Override
	public boolean getAutoCommit() throws SQLException {
		return connection.isAutoCommit();
	}

	@Override
	public void commit() throws SQLException {
		connection.commit(false);
	}

	@Override
	public void rollback() throws SQLException {
		connection.rollback(false);
	}

	@Override
	public void close() throws SQLException {
		connection.close();
	}

	@Override
	public boolean isClosed() throws SQLException {
		return !connection.isOpen();
	}

	@Override
	public void setReadOnly(boolean readOnly) throws SQLException {
		connection.setReadonly(readOnly);
	}

	@Override
	public boolean isReadOnly() throws SQLException {
		return connection.isReadonly();
	}

	@Override
	public void setTransactionIsolation(int level) throws SQLException {
		connection.setIsolationLevel(level);
	}

	@Override
	public int getTransactionIsolation() throws SQLException {
		return connection.getIsolationLevel();
	}

	@Override
	public Statement createStatement(int resultSetType, int resultSetConcurrency) throws SQLException {
		return createStatement(resultSetType, resultSetConcurrency, ResultSet.CLOSE_CURSORS_AT_COMMIT);
	}

	@Override
	public PreparedStatement prepareStatement(String sql, int resultSetType, int resultSetConcurrency) throws SQLException {
		return prepareStatement(sql, resultSetType, resultSetConcurrency, ResultSet.CLOSE_CURSORS_AT_COMMIT);
	}

	@Override
	public CallableStatement prepareCall(String sql, int resultSetType, int resultSetConcurrency) throws SQLException {
		return prepareCall(sql, resultSetType, resultSetConcurrency, ResultSet.CLOSE_CURSORS_AT_COMMIT);
	}

	@Override
	public Savepoint setSavepoint() throws SQLException {
		return connection.setSavepoint();
	}

	@Override
	public Savepoint setSavepoint(String name) throws SQLException {
		return connection.setSavepoint(name);
	}

	@Override
	public void rollback(Savepoint savepoint) throws SQLException {
		connection.rollbackToSavepoint(savepoint);
	}

	@Override
	public void releaseSavepoint(Savepoint savepoint) throws SQLException {
		connection.releaseSavepoint(savepoint);
	}

	@Override
	public Statement createStatement(int resultSetType, int resultSetConcurrency, int resultSetHoldability) throws SQLException {
		return new JStatement(this, resultSetType, resultSetConcurrency, resultSetHoldability);
	}

	@Override
	public PreparedStatement prepareStatement(String sql, int resultSetType, int resultSetConcurrency, int resultSetHoldability) throws SQLException {
		return new JPreparedStatement(sql, this, resultSetType, resultSetConcurrency, resultSetHoldability);
	}

	@Override
	public CallableStatement prepareCall(String sql, int resultSetType, int resultSetConcurrency, int resultSetHoldability) throws SQLException {
		return new JPreparedCall(sql, this, resultSetType, resultSetConcurrency, resultSetHoldability);
	}

	@Override
	public PreparedStatement prepareStatement(String sql, int autoGeneratedKeys) throws SQLException {
		return new JPreparedStatement(sql, this, autoGeneratedKeys == Statement.RETURN_GENERATED_KEYS ? GenerateKeyReturnOper.RETURN_KEY : GenerateKeyReturnOper.NONE);
	}

	@Override
	public PreparedStatement prepareStatement(String sql, int[] columnIndexes) throws SQLException {
		return new JPreparedStatement(sql, this, new GenerateKeyReturnOper.ReturnByColumnIndex(columnIndexes));
	}

	@Override
	public PreparedStatement prepareStatement(String sql, String[] columnNames) throws SQLException {
		return new JPreparedStatement(sql, this, new GenerateKeyReturnOper.ReturnByColumnNames(columnNames));
	}

	@Override
	public Clob createClob() throws SQLException {
		return conn().createClob();
	}

	@Override
	public Blob createBlob() throws SQLException {
		return conn().createBlob();
	}

	@Override
	public NClob createNClob() throws SQLException {
		return conn().createNClob();
	}

	@Override
	public SQLXML createSQLXML() throws SQLException {
		return conn().createSQLXML();
	}

	@Override
	public boolean isValid(int timeout) throws SQLException {
		return conn().isValid(timeout);
	}

	@Override
	public void setClientInfo(String name, String value) throws SQLClientInfoException {
		try {
			conn().setClientInfo(name, value);
		} catch (SQLException e) {
			throw new SQLClientInfoException();
		}
	}

	@Override
	public void setClientInfo(Properties properties) throws SQLClientInfoException {
		try {
			conn().setClientInfo(properties);
		} catch (SQLException e) {
			throw new SQLClientInfoException();
		}
	}

	@Override
	public String getClientInfo(String name) throws SQLException {
		return conn().getClientInfo(name);
	}

	@Override
	public Properties getClientInfo() throws SQLException {
		return conn().getClientInfo();
	}

	@Override
	public Array createArrayOf(String typeName, Object[] elements) throws SQLException {
		return conn().createArrayOf(typeName, elements);
	}

	@Override
	public Struct createStruct(String typeName, Object[] attributes) throws SQLException {
		return conn().createStruct(typeName, attributes);
	}

	public <T> T unwrap(Class<T> iface) throws SQLException {
		throw new UnsupportedOperationException();
	}

	public boolean isWrapperFor(Class<?> iface) throws SQLException {
		return false;
	}

	@Override
	public String nativeSQL(String sql) throws SQLException {
		return conn().nativeSQL(sql);
	}

	private Connection conn() throws SQLException {
		return (Connection) DebugUtil.getIConnection(connection);
	}

	@Override
	public DatabaseMetaData getMetaData() throws SQLException {
		return conn().getMetaData();
	}

	@Override
	public void setCatalog(String catalog) throws SQLException {
		conn().setCatalog(catalog);
	}

	@Override
	public String getCatalog() throws SQLException {
		return conn().getCatalog();
	}

	@Override
	public SQLWarning getWarnings() throws SQLException {
		return conn().getWarnings();
	}

	@Override
	public void clearWarnings() throws SQLException {
		conn().clearWarnings();
	}

	@Override
	public Map<String, Class<?>> getTypeMap() throws SQLException {
		return conn().getTypeMap();
	}

	@Override
	public void setTypeMap(Map<String, Class<?>> map) throws SQLException {
		conn().setTypeMap(map);
	}

	@Override
	public void setHoldability(int holdability) throws SQLException {
		conn().setHoldability(holdability);
	}

	@Override
	public int getHoldability() throws SQLException {
		return conn().getHoldability();
	}

	public WrappedConnection get() {
		return this.connection;
	}
}
