package jef.database.covertformdb;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import jef.codegen.support.NotModified;
import jef.database.DataObject;
/**
 * This class was generated by JEF according to the table in database.
 * You need to modify the type of primary key field, to the strategy your own.
 */
@NotModified
@Entity
@Table(name="user")
public class User extends DataObject{


	@GeneratedValue(strategy=GenerationType.SEQUENCE)
	@SequenceGenerator(name="",sequenceName="fetstabstr_SEQ")
	@Id
	@Column(name="i_id",precision=10,columnDefinition="number(10)",nullable=false)
	private int id;

	@Column(name="s_username",columnDefinition="varchar(64)",length=64,nullable=false)
	private String username;

	@Column(name="s_password",columnDefinition="varchar(64)",length=64,nullable=false)
	private String password;

	@Column(name="s_fullname",columnDefinition="varchar(64)",length=64)
	private String fullname;

	@Column(name="s_email",columnDefinition="varchar(64)",length=64)
	private String email;

	public void setId(int obj){
		this.id = obj;
	}

	public int getId(){
		return id;
	}

	public void setUsername(String obj){
		this.username = obj;
	}

	public String getUsername(){
		return username;
	}

	public void setPassword(String obj){
		this.password = obj;
	}

	public String getPassword(){
		return password;
	}

	public void setFullname(String obj){
		this.fullname = obj;
	}

	public String getFullname(){
		return fullname;
	}

	public void setEmail(String obj){
		this.email = obj;
	}

	public String getEmail(){
		return email;
	}

	public User(){
	}

	public User(int id){
		this.id = id;
	}


public enum Field implements jef.database.Field{id,username,password,fullname,email}
}