package jef.database.test.covertfromdb;

import javax.persistence.Table;
import jef.database.DataObject;
import javax.persistence.Id;
import javax.persistence.GenerationType;
import javax.persistence.GeneratedValue;
import javax.persistence.Column;
import javax.persistence.Entity;
import jef.codegen.support.NotModified;
/**
 * This class was generated by JEF according to the table in database.
 * You need to modify the type of primary key field, to the strategy your own.
 */
@NotModified
@Entity
@Table(name="user")
public class User extends DataObject{


	@GeneratedValue(strategy=GenerationType.SEQUENCE)
	@Id
	@Column(name="i_id",precision=10,columnDefinition="number(10)",nullable=false)
	private int iId;

	@Column(name="s_username",columnDefinition="varchar(64)",length=64,nullable=false)
	private String sUsername;

	@Column(name="s_password",columnDefinition="varchar(64)",length=64,nullable=false)
	private String sPassword;

	@Column(name="s_fullname",columnDefinition="varchar(64)",length=64)
	private String sFullname;

	@Column(name="s_email",columnDefinition="varchar(64)",length=64)
	private String sEmail;

	public void setIId(int obj){
		this.iId = obj;
	}

	public int getIId(){
		return iId;
	}

	public void setSUsername(String obj){
		this.sUsername = obj;
	}

	public String getSUsername(){
		return sUsername;
	}

	public void setSPassword(String obj){
		this.sPassword = obj;
	}

	public String getSPassword(){
		return sPassword;
	}

	public void setSFullname(String obj){
		this.sFullname = obj;
	}

	public String getSFullname(){
		return sFullname;
	}

	public void setSEmail(String obj){
		this.sEmail = obj;
	}

	public String getSEmail(){
		return sEmail;
	}

	public User(){
	}

	public User(int iId){
		this.iId = iId;
	}


public enum Field implements jef.database.Field{iId,sUsername,sPassword,sFullname,sEmail}
}